name: Publish

on:
  push:
    branches: [master]

jobs:
  build-n-publish:
    name: Publish bmaclient to Pypi package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Build binary
        run: |
          python -m pip install build --user
          python -m build --sdist --wheel --outdir dist/

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
